default_platform(:ios)

platform :ios do
  desc "Build for App Store"
  lane :release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "../build/ios",
    )
  end

  desc "Take screenshots"
  lane :screenshots do
    capture_screenshots
  end
end
